import Config  from '~/Constants/Config';

export default {
    Pages:     {
        PostLink:             'Pages/Post.php?PostID={postId}',
        EventLink:            'Pages/Event.php?EventID={eventId}',
        AllNotes:             'Pages/Search-List.php?List=Notes',
        AllEvents:            'Pages/Search-List.php?List=Events',
        AllNewsLink:          'Login/Profile.php?Char=Gods+Of+Zushin',
        AboutUs:              'Pages/About.php',
        TC:                   'Pages/TC-Policy.php',
        Policy:               'Pages/TC-Policy.php',
        Facebook:             'https://facebook.com/godsofzushin/',
        YouTube:              'https://www.youtube.com/channel/UCzPbZJ-T0GJG_RUKB33qy1w?view_as=subscriber',
        Discord:              'https://discord.gg/yS23nZA',
        Telegram:             'https://t.me/gozushin',
        ContantUs:            'https://facebook.com/godsofzushin/inbox/',
        Guides:               'https://facebook.com/pg/godsofzushin/notes/?ref=page_internal',
        ChargeZP:             '/charge',
        ExchangeZP:           '/exchange',
        ExchangeTransactions: '/transactions',
        RedeemEventRewards:   '/redeem-event-gift',
        RedeemGift:           '/redeem-gift',
        Shop:                 '/shop',
        BuildCharacter:       '/build-character',
        Forum:                '/forum',
        Feed:                 '/feed',
        Post:                 '/post',
        Event:                '/event',
        Album:                '/album',
        Advert:               '/advert',
        Note:                 '/note',
        Profile:              '/profile',
        Logout:               '/logout',
        Login:                '/login',
        Register:             '/register',
        Recovery:             '/recovery',
        Main:                 '/main',
        Home:                 '/home',
    },
    EndPoints: {
        API:         'API',
        UploadFiles: `${Config.API.nodeJsEndPoint}/UploadFiles`,
    },
};
